export const rankAbbreviations: Record<string, string> = {
  '' : '',
  'Airman Basic': 'AB',
  'Airman': 'Amn',
  'Airman First Class': 'A1C',
  'Senior Airman': 'SrA',
  'Staff Sergeant': 'SSgt',
  'Technical Sergeant': 'TSgt',
  'Master Sergeant': 'MSgt',
  'Senior Master Sergeant': 'SMSgt',
  'Chief Master Sergeant': 'CMSgt',
  'Command Chief Master Sergeant': 'CCM',
  'Chief Master Sergeant of the Air Force': 'CMSAF',
  'Second Lieutenant': '2d Lt',
  'First Lieutenant': '1st Lt',
  'Captain': 'Capt',
  'Major': 'Maj',
  'Lieutenant Colonel': 'Lt Col',
  'Colonel': 'Col',
  'Brigadier General': 'Brig Gen',
  'Major General': 'Maj Gen',
  'Lieutenant General': 'Lt Gen',
  'General': 'Gen',
  'General of the Air Force': 'GAF',
};